//
// This file was automatically generated by wxrc, do not edit by hand.
//

#ifndef __xrcres_h__
#define __xrcres_h__
class MainFrameBase : public wxFrame {
protected:
 wxPanel* General;
 wxCheckBox* Enabled;
 wxCheckBox* Training;
 wxCheckBox* BeepForMistakes;
 wxCheckBox* RunAtStartup;
 wxCheckBox* ShowInNotificationArea;
 wxCheckBox* CheckForUpdates;
 wxListBox* KeyList;
 wxButton* AddBindingButton;
 wxButton* EditBindingButton;
 wxButton* RemoveBindingButton;
 wxButton* DefaultsButton;
 wxChoice* ActivationKeys;
 wxPanel* Programs;
 wxPanel* About;
 wxHtmlWindow* LicenseText;
 wxButton* HelpButton;
 wxButton* WebSiteButton;
 wxButton* CheckForUpdateButton;
 wxButton* DonateButton;
 wxButton* OkButton;
 wxButton* CancelButton;
 wxButton* ApplyButton;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,_T("MainFrameBase"), _T("wxFrame"));
  General = XRCCTRL(*this,"General",wxPanel);
  Enabled = XRCCTRL(*this,"Enabled",wxCheckBox);
  Training = XRCCTRL(*this,"Training",wxCheckBox);
  BeepForMistakes = XRCCTRL(*this,"BeepForMistakes",wxCheckBox);
  RunAtStartup = XRCCTRL(*this,"RunAtStartup",wxCheckBox);
  ShowInNotificationArea = XRCCTRL(*this,"ShowInNotificationArea",wxCheckBox);
  CheckForUpdates = XRCCTRL(*this,"CheckForUpdates",wxCheckBox);
  KeyList = XRCCTRL(*this,"KeyList",wxListBox);
  AddBindingButton = XRCCTRL(*this,"AddBindingButton",wxButton);
  EditBindingButton = XRCCTRL(*this,"EditBindingButton",wxButton);
  RemoveBindingButton = XRCCTRL(*this,"RemoveBindingButton",wxButton);
  DefaultsButton = XRCCTRL(*this,"DefaultsButton",wxButton);
  ActivationKeys = XRCCTRL(*this,"ActivationKeys",wxChoice);
  Programs = XRCCTRL(*this,"Programs",wxPanel);
  About = XRCCTRL(*this,"About",wxPanel);
  LicenseText = XRCCTRL(*this,"LicenseText",wxHtmlWindow);
  HelpButton = XRCCTRL(*this,"HelpButton",wxButton);
  WebSiteButton = XRCCTRL(*this,"WebSiteButton",wxButton);
  CheckForUpdateButton = XRCCTRL(*this,"CheckForUpdateButton",wxButton);
  DonateButton = XRCCTRL(*this,"DonateButton",wxButton);
  OkButton = XRCCTRL(*this,"OkButton",wxButton);
  CancelButton = XRCCTRL(*this,"CancelButton",wxButton);
  ApplyButton = XRCCTRL(*this,"ApplyButton",wxButton);
 }
public:
MainFrameBase(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class ProgListDialogBase : public wxDialog {
protected:
 wxListBox* ProgList;
 wxStaticBitmap* DragIcon;
 wxButton* RemoveButton;
 wxButton* wxID_OK;
 wxButton* wxID_CANCEL;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,_T("ProgListDialogBase"), _T("wxDialog"));
  ProgList = XRCCTRL(*this,"ProgList",wxListBox);
  DragIcon = XRCCTRL(*this,"DragIcon",wxStaticBitmap);
  RemoveButton = XRCCTRL(*this,"RemoveButton",wxButton);
  wxID_OK = XRCCTRL(*this,"wxID_OK",wxButton);
  wxID_CANCEL = XRCCTRL(*this,"wxID_CANCEL",wxButton);
 }
public:
ProgListDialogBase(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class BindingDialogBase : public wxDialog {
protected:
 wxStaticText* ActivationKeyLabel;
 wxTextCtrl* KeyToPress;
 wxButton* KeyToPressButton;
 wxCheckBox* Shift;
 wxCheckBox* Ctrl;
 wxCheckBox* Alt;
 wxCheckBox* Win;
 wxTextCtrl* KeyToGenerate;
 wxButton* KeyToGenerateButton;
 wxButton* wxID_OK;
 wxButton* wxID_CANCEL;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,_T("BindingDialogBase"), _T("wxDialog"));
  ActivationKeyLabel = XRCCTRL(*this,"ActivationKeyLabel",wxStaticText);
  KeyToPress = XRCCTRL(*this,"KeyToPress",wxTextCtrl);
  KeyToPressButton = XRCCTRL(*this,"KeyToPressButton",wxButton);
  Shift = XRCCTRL(*this,"Shift",wxCheckBox);
  Ctrl = XRCCTRL(*this,"Ctrl",wxCheckBox);
  Alt = XRCCTRL(*this,"Alt",wxCheckBox);
  Win = XRCCTRL(*this,"Win",wxCheckBox);
  KeyToGenerate = XRCCTRL(*this,"KeyToGenerate",wxTextCtrl);
  KeyToGenerateButton = XRCCTRL(*this,"KeyToGenerateButton",wxButton);
  wxID_OK = XRCCTRL(*this,"wxID_OK",wxButton);
  wxID_CANCEL = XRCCTRL(*this,"wxID_CANCEL",wxButton);
 }
public:
BindingDialogBase(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class KeyDialogBase : public wxDialog {
protected:
 wxListBox* KeyList;
 wxButton* wxID_OK;
 wxButton* wxID_CANCEL;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,_T("KeyDialogBase"), _T("wxDialog"));
  KeyList = XRCCTRL(*this,"KeyList",wxListBox);
  wxID_OK = XRCCTRL(*this,"wxID_OK",wxButton);
  wxID_CANCEL = XRCCTRL(*this,"wxID_CANCEL",wxButton);
 }
public:
KeyDialogBase(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};

void 
InitXmlResource();
#endif
